# -*- coding: utf-8 -*-
"""Sentiment_Analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCYc5dJjNus9rRoTVLr4t9E6_Kpu0ugy
"""

# ✅ ONE-CELL SENTIMENT ANALYSIS (Colab-ready)
# - Creates its own dataset (no external files)
# - Runs lexicon-based sentiment analysis
# - Shows chart, saves CSV/PNG, and downloads them

# (1) Imports
import re, random
import pandas as pd
import matplotlib.pyplot as plt

# (2) Make a small dataset right here (so no FileNotFoundError)
positive = [
    "I love this", "This is awesome", "Feeling great today",
    "What a fantastic result", "Super happy with the progress",
    "Brilliant idea", "Absolutely wonderful", "This made my day",
    "Excited to learn more", "Proud of this work", "Great job team",
    "Amazing experience", "Positive vibes only", "Delicious and perfect",
    "Highly recommended", "So satisfied with the outcome"
]
negative = [
    "I hate this", "This is terrible", "Feeling bad today",
    "What a disappointing result", "Really unhappy with the progress",
    "Awful idea", "Absolutely horrible", "This ruined my day",
    "Frustrated and tired", "Not proud of this", "Poor job team",
    "Terrible experience", "Negative vibes", "Disgusting and awful",
    "Not recommended", "So dissatisfied with the outcome"
]
neutral = [
    "Working on a new project", "Today is Wednesday", "Reading documentation",
    "The meeting is at 3 pm", "I am testing a script", "Data loaded successfully",
    "Need to refactor code", "The weather is fine", "Checking the results",
    "Pushing code to GitHub", "This is a sample text", "Learning new tools",
    "Attending an online class", "Writing a report", "Running experiments"
]

random.seed(42)
rows = []
for _ in range(120):
    bucket = random.choices([positive, negative, neutral], weights=[0.4, 0.35, 0.25], k=1)[0]
    txt = random.choice(bucket) + random.choice(["!", ".", " :)", " :(", " ...", ""])
    rows.append({"text": txt})

df = pd.DataFrame(rows)

# (3) Tiny lexicon (self-contained)
POS = {
    "love","awesome","great","fantastic","happy","brilliant","wonderful",
    "excited","proud","amazing","positive","delicious","perfect","recommended",
    "satisfied","good","best","nice","cool","win","success"
}
NEG = {
    "hate","terrible","bad","disappointing","unhappy","awful","horrible","ruined",
    "frustrated","tired","poor","negative","disgusting","dissatisfied","fail",
    "worst","bug","issue","angry","sad","broken"
}

def tokenize(s: str):
    return re.findall(r"[a-zA-Z']+", s.lower())

def score_text(s: str):
    tokens = tokenize(s)
    pos = sum(1 for t in tokens if t in POS)
    neg = sum(1 for t in tokens if t in NEG)
    score = pos - neg
    if score > 0: label = "Positive"
    elif score < 0: label = "Negative"
    else: label = "Neutral"
    return score, label, pos, neg

# (4) Analyze
results = []
for i, s in enumerate(df["text"].astype(str)):
    sc, lab, p, n = score_text(s)
    results.append({"id": i, "text": s, "pos_hits": p, "neg_hits": n, "score": sc, "label": lab})

res_df = pd.DataFrame(results)
res_df.head()
print(res_df["label"].value_counts())

# (5) Plot
counts = res_df["label"].value_counts().reindex(["Positive","Neutral","Negative"]).fillna(0)
plt.figure(figsize=(8,5))
counts.plot(kind="bar")
plt.title("Sentiment Label Counts")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# (6) Save outputs
res_df.to_csv("sentiment_results.csv", index=False)
plt.figure(figsize=(8,5))
counts.plot(kind="bar")
plt.title("Sentiment Label Counts")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("sentiment_counts.png")
print("Saved: sentiment_results.csv, sentiment_counts.png")

# (7) Auto-download (works in Colab)
try:
    from google.colab import files
    files.download("sentiment_results.csv")
    files.download("sentiment_counts.png")
except Exception as e:
    print("Download note:", e, "\nIf not on Colab, manually download from the left Files panel.")
!pip install pandas matplotlib